### ISSUE TITLE
[ Bug ] RPS with invalid 'custom_id'

### ISSUE THREAD

**Issue by Aid0nModder** [Aid0nModder/AidanBot#121]
```
﻿Traceback (most recent call last):
﻿File "/opt/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 827, in _do_call
﻿return await self._callback(self.binding, interaction, **params)  # type: ignore
﻿File "/app/cogs/games.py", line 101, in rps
﻿player1.pick = butitr.data["custom_id"]
﻿KeyError: 'custom_id'
﻿The above exception was the direct cause of the following exception:
﻿Traceback (most recent call last):
﻿File "/opt/venv/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1248, in _call
﻿await command._invoke_with_namespace(interaction, namespace)
﻿File "/opt/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
﻿return await self._do_call(interaction, transformed_values)
﻿File "/opt/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 846, in _do_call
﻿raise CommandInvokeError(self, e) from e
﻿discord.app_commands.errors.CommandInvokeError: Command 'rps' raised an exception: KeyError: 'custom_id'
```

**Comment by Aid0nModder** [comment]
Fixed, merging changes now
